// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuzunoxncedujvtqrwsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1enVub3huY2VkdWp2dHFyd3N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2Njc3NTAsImV4cCI6MjA3MzI0Mzc1MH0.I6GxZ_UXA5TQNxvaJCW0i-BN7N1LuYj-FGfaoecOe7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});